---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker directory exists
      ansible.builtin.file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: "0755"
